<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BookingController;

/*
|--------------------------------------------------------------------------
| Api Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

Route::name('api.')
    ->prefix('api')
    ->group(function () {
        Route::post('/register', [AuthController::class, 'register'])->name('register');

        Route::post('/login', [AuthController::class, 'login'])->name(
            'api.login'
        );
        

        Route::middleware('auth:sanctum')->group(function () {

            Route::get('/services', [BookingController::class, 'index'])->name(
                'services.index'
            );

            // Route::get('/bookings', [BookingController::class, 'index'])->name(
            //     'bookings.index'
            // );

            Route::post('/bookings', [BookingController::class, 'store'])->name(
                'bookings.store'
            );

            Route::get('/bookings/{booking}', [
                BookingController::class,
                'show',
            ])->name('bookings.show');

            Route::put('/bookings/{booking}', [
                BookingController::class,
                'update',
            ])->name('bookings.update');

            Route::delete('/bookings/{booking}', [
                BookingController::class,
                'destroy',
            ])->name('bookings.destroy');

            Route::post('logout', [AuthController::class, 'logout'])->name('logout');

        });
    });
