<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

// Dashboard
Route::prefix('/dashboard')
    ->name('dashboard.')
    ->group(function () {
        Route::get(
            '/services',
            App\Livewire\Dashboard\ServiceIndex::class
        )->name('services.index');

        Route::get(
            '/services/create',
            App\Livewire\Dashboard\ServiceCreate::class
        )->name('services.create');

        Route::get(
            '/services/{service}',
            App\Livewire\Dashboard\ServiceEdit::class
        )->name('services.edit');

        Route::get(
            '/sub-services',
            App\Livewire\Dashboard\SubServiceIndex::class
        )->name('sub-services.index');

        Route::get(
            '/sub-services/create',
            App\Livewire\Dashboard\SubServiceCreate::class
        )->name('sub-services.create');

        Route::get(
            '/sub-services/{subService}',
            App\Livewire\Dashboard\SubServiceEdit::class
        )->name('sub-services.edit');

        Route::get(
            '/sub-service-templates',
            App\Livewire\Dashboard\SubServiceTemplateIndex::class
        )->name('sub-service-templates.index');

        Route::get(
            '/sub-service-templates/create',
            App\Livewire\Dashboard\SubServiceTemplateCreate::class
        )->name('sub-service-templates.create');

        Route::get(
            '/sub-service-templates/{subServiceTemplate}',
            App\Livewire\Dashboard\SubServiceTemplateEdit::class
        )->name('sub-service-templates.edit');

        Route::get(
            '/all-delivery-days',
            App\Livewire\Dashboard\DeliveryDaysIndex::class
        )->name('all-delivery-days.index');

        Route::get(
            '/all-delivery-days/create',
            App\Livewire\Dashboard\DeliveryDaysCreate::class
        )->name('all-delivery-days.create');

        Route::get(
            '/all-delivery-days/{deliveryDays}',
            App\Livewire\Dashboard\DeliveryDaysEdit::class
        )->name('all-delivery-days.edit');

        Route::get(
            '/content-categories',
            App\Livewire\Dashboard\ContentCategoryIndex::class
        )->name('content-categories.index');

        Route::get(
            '/content-categories/create',
            App\Livewire\Dashboard\ContentCategoryCreate::class
        )->name('content-categories.create');

        Route::get(
            '/content-categories/{contentCategory}',
            App\Livewire\Dashboard\ContentCategoryEdit::class
        )->name('content-categories.edit');

        Route::get(
            '/influencers',
            App\Livewire\Dashboard\InfluencerIndex::class
        )->name('influencers.index');

        Route::get(
            '/influencers/create',
            App\Livewire\Dashboard\InfluencerCreate::class
        )->name('influencers.create');

        Route::get(
            '/influencers/{influencer}',
            App\Livewire\Dashboard\InfluencerEdit::class
        )->name('influencers.edit');
    });

// API
Route::prefix('/api')
    ->name('api.')
    ->group(function () {});

// Site
Route::prefix('/')->group(function () {});

// Filament Panel
Route::prefix('/panel')
    ->name('panel.')
    ->group(function () {});
